name: Hexo Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "848494675@qq.com"
          git config --global user.name "reol"
          npm install hexo-cli -g
          npm install

      - name: Deploy
        run: |
          hexo clean
          hexo deploy

      - name: 📂Sync files
        # uses: swillner/sftp-sync-action@v1.0 
        uses: wlixcc/SFTP-Deploy-Action@v1.0 
        with:
          server: '${{ secrets.FTP_SERVER }}'
          username: 'root'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './public/*' 
          remote_path: '/home/rn/hexo'